# Notice we use the HOSTNAME here, not the IP, for TLS validation
ansible_host: hostname_1 
nas_shared_folder: '\\your_nas_name\backup_folder_1'
nas_task_guid: "YOUR-HASLEO-TASK-GUID-1"
ansible_winrm_ca_trust_path: /home/ubuntu24/ansible-backup-orchestrator/certs/hostname_1-winrm.pem

ansible_user: "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"
nas_username: "{{ vault_nas_username }}"
nas_password: "{{ vault_nas_password }}"